export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentFailureCode {
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  WEBHOOK_DUPLICATE = 'WEBHOOK_DUPLICATE',
  GATEWAY_ERROR = 'GATEWAY_ERROR',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
}